### ISSUE TITLE
Reduce mixins which could be replaced by PostCSS

### ISSUE THREAD

**Issue by seleckis** [jackbrewer/stylus-mixins#13]
PostCSS becomes extremely popular today. I suggest to reduce those mixing which could duplicated by PostCSS actions. What do you think?

**Comment by jackbrewer** [comment]
I'd rather not, at least not yet. PostCSS isn't used by everyone (including me) so I wouldn't like to remove mixins. 

My current opinion would be that this could live side-by-side with your PostCSS actions - you don't have to use all the mixins here, only the ones you need.

**Comment by seleckis** [comment]
No problem. Ihave already developed my own fork of nib and removed all mixins which just add vendor prefixes. Cheers!
