### ISSUE TITLE
Opacity mixin doesn't override -ms-filter in IE8

### ISSUE THREAD

**Issue by pvalentim** [jackbrewer/stylus-mixins#7]
If you set an opacity value on an element and then try to override it to be 1 with a modifier class for example it doesn't work.

The reason is that for opacity 1 the mixin sets -ms-filter and filter to none. This doesn't seem to work for some reason, I found that -ms-filter: '-'; works.

Working on PR for this

**Comment by jackbrewer** [comment]
Ran into this one again today. Fixed by removing logic checking for `if $val == 100`.

`opacity 1` will now output the following rather than the broken `none` values.
```
filter: alpha(opacity=100);
-ms-filter:"progid:DXImageTransform.Microsoft.Alpha(opacity=100)";
```
